# Generated by Django 4.2 on 2023-04-18 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('age_unit', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repot_number', models.CharField(max_length=20)),
                ('date_created', models.CharField(max_length=20)),
                ('date_started', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=500)),
                ('reactions', models.CharField(max_length=500)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_event.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('name_brand', models.CharField(max_length=200)),
                ('inductry_code', models.CharField(max_length=20)),
                ('inductry_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_event.foodadverseevent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_event.product')),
            ],
        ),
        migrations.AddField(
            model_name='foodadverseevent',
            name='products',
            field=models.ManyToManyField(through='search_event.ProductEvent', to='search_event.product'),
        ),
    ]
