# Generated by Django 4.2 on 2023-04-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='age_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='consumer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_event.consumer'),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='date_created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='date_started',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='outcome',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='products',
            field=models.ManyToManyField(null=True, through='search_event.ProductEvent', to='search_event.product'),
        ),
        migrations.AlterField(
            model_name='foodadverseevent',
            name='reactions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inductry_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inductry_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
