# Generated by Django 4.2 on 2023-04-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_event', '0002_alter_consumer_age_alter_consumer_age_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodadverseevent',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_event.consumer'),
        ),
    ]
